### ISSUE TITLE
Hacer una estructura de comandos más simple

### ISSUE THREAD

**Issue by jc-discdev** [shofy-js/shofy#11]
Creo que sería mejor hacer una estructura más simple de los comandos por si alguien quiere añadir sus propios comandos que no tenga fallos. Ya que la actual es muy complicada.

**Comment by chiquicalris-dev** [comment]
El modelo de comandos actual está realizado para los `fields` de los diferentes slashs commands
```js
module.exports = {
	name: 'ping',
	description:
		'Ping pong! Here you can receive the current response time of the bot.',
	commandOptions: null,
	global: true,
	execute(interaction) {
		client.api.interactions(interaction.id, interaction.token).callback.post({
			data: {
				type: 4,
				data: {
					content: `:ping_pong: Pong: ${client.ws.ping}!`,
				},
			},
		});
	},
};
```

**Comment by chiquicalris-dev** [comment]
El campo `Description` es la descripción que se mostrará en el comando, y el `commandOptions` son las diferentes variables que a su vez se emplean en este tipo de comandos.

**Comment by jc-discdev** [comment]
Creo que sería mejor hacerlo que también pueda ser sin slash commands.

**Comment by chiquicalris-dev** [comment]
Al igual que comenté con la issue de los "i18n" los comandos slashs es lo que nos espera a todos los desarrolladores que trabajamos con discord.js, y al igual que he comentado allí es mejor comenzar a implementarlo ahora que cuando tengamos alrededor de ~70 comandos.

**Comment by jc-discdev** [comment]
De acuerdo.
