### ISSUE TITLE
Implementación del sistema i18n

### ISSUE THREAD

**Issue by chiquicalris-dev** [shofy-js/shofy#12]
Principalmente la realización del sistema `i18n` en este proyecto, para así poder facilitar en un futuro la traducción de los comandos, y en un futuro cercano evitar la necesidad de traducir una gran cantidad de comandos para la implementación de este sistema de traducciones.

Para que la comunidad pueda colaborar en el desarrollo de las diferentes traducciones podríamos emplear la siguiente página web, que a su vez la emplean diferentes proyectos como Mee6, Arcane o Gearbot.

> https://crowdin.com/

**Comment by jc-discdev** [comment]
Sería una buena forma de colaboración.
